FROM python:3.8

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt
COPY ./assets ./assets

WORKDIR /app

RUN pip install -r requirements.txt

COPY ./app /app

ENTRYPOINT [ "python" ]

CMD [ "AfluenceCounterApp.py" ]

Expose 5000